"""
Factory defaults for all configurable project settings.
Every key here can be overridden per project in a saved profile.
"""

import copy

SETTINGS_SCHEMA = {
    # ── Customers / Parties ───────────────────────────────────────────────
    "customers": {
        "customer_group_id": "40",
        "customer_last_name_suffix": "Default Customer",
        "customer_address_book": "Cust_All",
        "staff_address_book": "Staff_All",
        "receipt_option": "RetailEx3",
    },
    # ── Store / Channel ───────────────────────────────────────────────────
    "store": {
        "product_category_hierarchy_name": "Frasers Group Product Hierarchy",
        "operating_unit_prefix": "B",
        "price_includes_sales_tax": "Yes",
        "maximum_text_length_on_receipt": "39",
        "layout_id_pattern": "SD_{country}",
        "tax_group_pattern": "{country_code_upper}_DOM_CUS",
        "dimension_display_value_pattern": "-{store_id}-STORE-SDR-",
    },
    # ── Warehouse / Inventory ─────────────────────────────────────────────
    "warehouse": {
        "inventory_status_id": "ACTIVE",
    },
    # ── Hardware Station ──────────────────────────────────────────────────
    "hardware": {
        "hardware_profile_pattern": "{country_code}-PhysPED",
    },
    # ── Timezone ──────────────────────────────────────────────────────────
    "timezone": {
        "site_timezone": "GMT_CASABLANCA_MONTROVIA_REYKJAVIK",
        "channel_timezone": "GMT_CASABLANCA_MONTROVIA_REYKJAVIK",
        "channel_timezone_info_id": "GREENWICH STANDARD TIME",
    },
    # ── Payment Methods ───────────────────────────────────────────────────
    "payment": {
        "tender_id_cash": "1",
        "tender_id_black_friday_voucher": "1023",
        "tender_id_credit_note": "631",
        "tender_id_gift_card": "650",
        "tender_id_card": "660",
        "tender_id_float_remove": "9999",
        "payment_method_to_remove": "9999",
        "card_connector_name": "FrasersConnector",
        "gift_card_item_id": "GiftCardExt",
        "info_code_id": "PaidIn/Out",
    },
    # ── Ledger Accounts ───────────────────────────────────────────────────
    "ledger_accounts": {
        "cash_ledger": "821701",
        "bank_bag_ledger": "821602",
        "difference_account": "119005",
        "eod_adj_plus_ledger": "119005",
        "eod_adj_minus_ledger": "119006",
        "paid_in_out_ledger": "821603",
        "safe_till_ledger": "119006",
        "coin_drop_ledger": "810105",
        "black_friday_voucher_ledger": "917023",
        "credit_note_ledger": "917012",
        "gift_card_ledger": "917002",
    },
}

# Human-readable labels for the settings dialog
SETTINGS_LABELS = {
    "customers": {
        "customer_group_id": "Customer Group ID",
        "customer_last_name_suffix": "Default Customer Last Name",
        "customer_address_book": "Customer Address Book",
        "staff_address_book": "Staff Address Book",
        "receipt_option": "Receipt Option (e.g. RetailEx3)",
    },
    "store": {
        "product_category_hierarchy_name": "Product Category Hierarchy Name",
        "operating_unit_prefix": "Operating Unit Prefix",
        "price_includes_sales_tax": "Price Includes Sales Tax (Yes/No)",
        "maximum_text_length_on_receipt": "Max Text Length on Receipt (chars)",
        "layout_id_pattern": "Layout ID Pattern  ({country} = 3-letter country)",
        "tax_group_pattern": "Tax Group Pattern  ({country_code_upper} = 2-letter code)",
        "dimension_display_value_pattern": "Dimension Display Value Pattern  ({store_id})",
    },
    "warehouse": {
        "inventory_status_id": "Default Inventory Status ID",
    },
    "hardware": {
        "hardware_profile_pattern": "Hardware Profile Pattern  ({country_code} = 2-letter code)",
    },
    "timezone": {
        "site_timezone": "Site Timezone (D365 enum)",
        "channel_timezone": "Channel Timezone (D365 enum)",
        "channel_timezone_info_id": "Channel Timezone Info ID (Windows)",
    },
    "payment": {
        "tender_id_cash": "Cash Tender ID",
        "tender_id_black_friday_voucher": "Black Friday Voucher Tender ID",
        "tender_id_credit_note": "Credit Note Tender ID",
        "tender_id_gift_card": "Gift Card Tender ID",
        "tender_id_card": "Card (EFT) Tender ID",
        "tender_id_float_remove": "Tender Remove/Float ID",
        "payment_method_to_remove": "Payment Method to Remove/Add (Store)",
        "card_connector_name": "Card Payment Connector Name",
        "gift_card_item_id": "Gift Card Item ID",
        "info_code_id": "Info Code ID for Paid In/Out",
    },
    "ledger_accounts": {
        "cash_ledger": "Cash Ledger Account",
        "bank_bag_ledger": "Bank Bag Ledger Account",
        "difference_account": "Difference Account (Over/Short)",
        "eod_adj_plus_ledger": "EOD Adjustment + Ledger",
        "eod_adj_minus_ledger": "EOD Adjustment - Ledger",
        "paid_in_out_ledger": "Paid In / Paid Out Ledger",
        "safe_till_ledger": "Safe <> Till Ledger",
        "coin_drop_ledger": "Coin Drop to Store Ledger",
        "black_friday_voucher_ledger": "Black Friday Voucher Ledger",
        "credit_note_ledger": "Credit Note Ledger",
        "gift_card_ledger": "Gift Card Ledger",
    },
}

TAB_LABELS = {
    "customers": "Customers",
    "store": "Store / Channel",
    "warehouse": "Warehouse",
    "hardware": "Hardware",
    "timezone": "Timezone",
    "payment": "Payment",
    "ledger_accounts": "Ledger Accounts",
}

D365_TIMEZONES = [
    "GMT_CASABLANCA_MONTROVIA_REYKJAVIK",
    "GMT_COORDINATED_UNIVERSAL_TIME",
    "GMT_MINUS_1_AZORES",
    "GMT_MINUS_2_MID_ATLANTIC",
    "GMT_MINUS_3_BRASILIA",
    "GMT_MINUS_3_BUENOS_AIRES_GEORGETOWN",
    "GMT_MINUS_3_GREENLAND",
    "GMT_MINUS_330_NEWFOUNDLAND",
    "GMT_MINUS_4_ATLANTIC_TIME_CANADA",
    "GMT_MINUS_4_MANAUS",
    "GMT_MINUS_4_SANTIAGO",
    "GMT_MINUS_430_CARACAS",
    "GMT_MINUS_5_BOGOTA_LIMA_QUITO_RIO_BRANCO",
    "GMT_MINUS_5_EASTERN_TIME_US_AND_CANADA",
    "GMT_MINUS_5_INDIANA_EAST",
    "GMT_MINUS_6_CENTRAL_AMERICA",
    "GMT_MINUS_6_CENTRAL_TIME_US_AND_CANADA",
    "GMT_MINUS_6_GUADALAJARA_MEXICO_CITY_MONTERREY",
    "GMT_MINUS_6_SASKATCHEWAN",
    "GMT_MINUS_7_ARIZONA",
    "GMT_MINUS_7_CHIHUAHUA_LA_PAZ_MAZATLAN",
    "GMT_MINUS_7_MOUNTAIN_TIME_US_AND_CANADA",
    "GMT_MINUS_8_PACIFIC_TIME_US_AND_CANADA",
    "GMT_MINUS_8_TIJUANA_BAJA_CALIFORNIA",
    "GMT_MINUS_9_ALASKA",
    "GMT_MINUS_10_HAWAII",
    "GMT_MINUS_11_MIDWAY_ISLAND_SAMOA",
    "GMT_MINUS_12_INTERNATIONAL_DATE_LINE_WEST",
    "GMT_PLUS_1_AMSTERDAM_BERLIN_BERN_ROME_STOCKHOLM_VIENNA",
    "GMT_PLUS_1_BELGRADE_BRATISLAVA_BUDAPEST_LJUBLJANA_PRAGUE",
    "GMT_PLUS_1_BRUSSELS_COPENHAGEN_MADRID_PARIS",
    "GMT_PLUS_1_SARAJEVO_SKOPJE_WARSAW_ZAGREB",
    "GMT_PLUS_1_WEST_CENTRAL_AFRICA",
    "GMT_PLUS_2_AMMAN",
    "GMT_PLUS_2_ATHENS_BUCHAREST_ISTANBUL",
    "GMT_PLUS_2_BEIRUT",
    "GMT_PLUS_2_CAIRO",
    "GMT_PLUS_2_HARARE_PRETORIA",
    "GMT_PLUS_2_HELSINKI_KYIV_RIGA_SOFIA_TALLINN_VILNIUS",
    "GMT_PLUS_2_JERUSALEM",
    "GMT_PLUS_2_MINSK",
    "GMT_PLUS_2_WINDHOEK",
    "GMT_PLUS_3_BAGHDAD",
    "GMT_PLUS_3_KUWAIT_RIYADH",
    "GMT_PLUS_3_MOSCOW_ST_PETERSBURG_VOLGOGRAD",
    "GMT_PLUS_3_NAIROBI",
    "GMT_PLUS_3_TBILISI",
    "GMT_PLUS_330_TEHRAN",
    "GMT_PLUS_4_ABU_DHABI_MUSCAT",
    "GMT_PLUS_4_BAKU",
    "GMT_PLUS_4_CAUCASUS_STANDARD_TIME",
    "GMT_PLUS_4_PORT_LOUIS",
    "GMT_PLUS_4_YEREVAN",
    "GMT_PLUS_430_KABUL",
    "GMT_PLUS_5_EKATERINBURG",
    "GMT_PLUS_5_ISLAMABAD_KARACHI",
    "GMT_PLUS_5_TASHKENT",
    "GMT_PLUS_530_CHENNAI_KOLKATA_MUMBAI_NEW_DELHI",
    "GMT_PLUS_530_SRI_JAYAWARDENEPURA",
    "GMT_PLUS_545_KATHMANDU",
    "GMT_PLUS_6_ALMATY_NOVOSIBIRSK",
    "GMT_PLUS_6_ASTANA_DHAKA",
    "GMT_PLUS_630_YANGON_RANGOON",
    "GMT_PLUS_7_BANGKOK_HANOI_JAKARTA",
    "GMT_PLUS_7_KRASNOYARSK",
    "GMT_PLUS_8_BEIJING_CHONGQING_HONG_KONG_URUMQI",
    "GMT_PLUS_8_IRKUTSK_ULAAN_BATAAR",
    "GMT_PLUS_8_KUALA_LUMPUR_SINGAPORE",
    "GMT_PLUS_8_PERTH",
    "GMT_PLUS_8_TAIPEI",
    "GMT_PLUS_9_OSAKA_SAPPORO_TOKYO",
    "GMT_PLUS_9_SEOUL",
    "GMT_PLUS_9_YAKUTSK",
    "GMT_PLUS_930_ADELAIDE",
    "GMT_PLUS_930_DARWIN",
    "GMT_PLUS_10_BRISBANE",
    "GMT_PLUS_10_CANBERRA_MELBOURNE_SYDNEY",
    "GMT_PLUS_10_GUAM_PORT_MORESBY",
    "GMT_PLUS_10_HOBART",
    "GMT_PLUS_10_VLADIVOSTOK",
    "GMT_PLUS_11_MAGADAN_SOLOMON_IS_NEW_CALEDONIA",
    "GMT_PLUS_12_AUCKLAND_WELLINGTON",
    "GMT_PLUS_12_FIJI_KAMCHATKA_MARSHALL_IS",
    "GMT_PLUS_13_NUKU_ALOFA",
]

WINDOWS_TIMEZONES = [
    "GREENWICH STANDARD TIME",
    "UTC",
    "ROMANCE STANDARD TIME",
    "CENTRAL EUROPEAN STANDARD TIME",
    "W. EUROPE STANDARD TIME",
    "E. EUROPE STANDARD TIME",
    "GTB STANDARD TIME",
    "MIDDLE EAST STANDARD TIME",
    "EGYPT STANDARD TIME",
    "SOUTH AFRICA STANDARD TIME",
    "FLE STANDARD TIME",
    "ISRAEL STANDARD TIME",
    "ARABIC STANDARD TIME",
    "ARAB STANDARD TIME",
    "RUSSIA TIME ZONE 2",
    "IRAN STANDARD TIME",
    "ARABIAN STANDARD TIME",
    "AZERBAIJAN STANDARD TIME",
    "GEORGIAN STANDARD TIME",
    "PAKISTAN STANDARD TIME",
    "INDIA STANDARD TIME",
    "SRI LANKA STANDARD TIME",
    "NEPAL STANDARD TIME",
    "CENTRAL ASIA STANDARD TIME",
    "BANGLADESH STANDARD TIME",
    "MYANMAR STANDARD TIME",
    "SE ASIA STANDARD TIME",
    "NORTH ASIA STANDARD TIME",
    "CHINA STANDARD TIME",
    "NORTH ASIA EAST STANDARD TIME",
    "SINGAPORE STANDARD TIME",
    "W. AUSTRALIA STANDARD TIME",
    "TAIPEI STANDARD TIME",
    "TOKYO STANDARD TIME",
    "KOREA STANDARD TIME",
    "YAKUTSK STANDARD TIME",
    "CEN. AUSTRALIA STANDARD TIME",
    "AUS CENTRAL STANDARD TIME",
    "E. AUSTRALIA STANDARD TIME",
    "AUS EASTERN STANDARD TIME",
    "WEST PACIFIC STANDARD TIME",
    "TASMANIA STANDARD TIME",
    "VLADIVOSTOK STANDARD TIME",
    "CENTRAL PACIFIC STANDARD TIME",
    "NEW ZEALAND STANDARD TIME",
    "FIJI STANDARD TIME",
    "TONGA STANDARD TIME",
    "EASTERN STANDARD TIME",
    "CENTRAL STANDARD TIME",
    "MOUNTAIN STANDARD TIME",
    "PACIFIC STANDARD TIME",
    "ALASKAN STANDARD TIME",
    "HAWAIIAN STANDARD TIME",
    "ATLANTIC STANDARD TIME",
    "SA EASTERN STANDARD TIME",
    "E. SOUTH AMERICA STANDARD TIME",
    "ARGENTINA STANDARD TIME",
    "GREENLAND STANDARD TIME",
    "NEWFOUNDLAND STANDARD TIME",
    "VENEZUELA STANDARD TIME",
    "SA WESTERN STANDARD TIME",
    "US EASTERN STANDARD TIME",
    "SA PACIFIC STANDARD TIME",
    "CANADA CENTRAL STANDARD TIME",
    "MEXICO STANDARD TIME 2",
    "US MOUNTAIN STANDARD TIME",
    "MEXICO STANDARD TIME",
    "PACIFIC SA STANDARD TIME",
    "UTC-02",
    "MID-ATLANTIC STANDARD TIME",
    "AZORES STANDARD TIME",
    "CAPE VERDE STANDARD TIME",
    "DATELINE STANDARD TIME",
    "SAMOA STANDARD TIME",
]


def get_default_settings() -> dict:
    """Return a deep copy of the factory default settings."""
    return copy.deepcopy(SETTINGS_SCHEMA)
