from .base import BaseGenerator


class WarehouseLocationsGenerator(BaseGenerator):

    @property
    def columns(self):
        return [
            "WAREHOUSEID", "WAREHOUSELOCATIONID", "AGINGDATE", "BINID",
            "DESTINATIONWAREHOUSELOCATIONID", "GENERATECHECKDIGITS",
            "ISDEFAULTCREDITONLYRETURNWAREHOUSELOCATION", "ISDEFAULTFINALSHIPMENTWAREHOUSELOCATION",
            "ISDEFAULTISSUEWAREHOUSELOCATION", "ISDEFAULTKANBANFINISHEDGOODSWAREHOUSELOCATION",
            "ISDEFAULTPRODUCTIONFINISHEDGOODSWAREHOUSELOCATION", "ISDEFAULTPRODUCTIONINPUTWAREHOUSELOCATION",
            "ISDEFAULTQUALITYMAINTENANCEWAREHOUSELOCATION", "ISDEFAULTRECEIPTWAREHOUSELOCATION",
            "ISDEFAULTRETAILSTORERETURNWAREHOUSELOCATION", "ISDEFAULTRETAILSTOREWAREHOUSELOCATION",
            "ISDEFAULTSHIPMENTMAINTENANCEWAREHOUSELOCATION", "ISDEFAULTSORTINGWAREHOUSELOCATION",
            "ISITEMINLOCATIONMAINTAINED", "ISLOCATIONACTIVITYDATETIMEMAINTAINED",
            "ISLOCATIONSTATUSMAINTAINED", "ISSORTORDERCODEMANUAL", "ISWAREHOUSELOCATIONIDMANUAL",
            "LASTACTIVITYDATETIME", "LASTCOUNTEDUTCDATETIME", "LOCATIONSTATUS",
            "PHYSICALDEPTH", "PHYSICALHEIGHT", "PHYSICALHEIGHTABOVEGROUND",
            "PHYSICALMAXIMUMSTORAGEVOLUME", "PHYSICALMAXIMUMSTORAGEWEIGHT", "PHYSICALWIDTH",
            "RACKID", "SHELFID", "SORTORDERCODE", "WAREHOUSEAISLEID", "WAREHOUSELOCATIONTYPE",
        ]

    def generate(self, stores):
        return [{
            "WAREHOUSEID": r["STOREID"],
            "WAREHOUSELOCATIONID": "Default",
            "AGINGDATE": "1900-01-01 00:00:00",
            "BINID": "0",
            "DESTINATIONWAREHOUSELOCATIONID": "Default",
            "GENERATECHECKDIGITS": "No",
            "ISDEFAULTCREDITONLYRETURNWAREHOUSELOCATION": "No",
            "ISDEFAULTFINALSHIPMENTWAREHOUSELOCATION": "No",
            "ISDEFAULTISSUEWAREHOUSELOCATION": "Yes",
            "ISDEFAULTKANBANFINISHEDGOODSWAREHOUSELOCATION": "No",
            "ISDEFAULTPRODUCTIONFINISHEDGOODSWAREHOUSELOCATION": "No",
            "ISDEFAULTPRODUCTIONINPUTWAREHOUSELOCATION": "No",
            "ISDEFAULTQUALITYMAINTENANCEWAREHOUSELOCATION": "No",
            "ISDEFAULTRECEIPTWAREHOUSELOCATION": "Yes",
            "ISDEFAULTRETAILSTORERETURNWAREHOUSELOCATION": "Yes",
            "ISDEFAULTRETAILSTOREWAREHOUSELOCATION": "Yes",
            "ISDEFAULTSHIPMENTMAINTENANCEWAREHOUSELOCATION": "No",
            "ISDEFAULTSORTINGWAREHOUSELOCATION": "No",
            "ISITEMINLOCATIONMAINTAINED": "No",
            "ISLOCATIONACTIVITYDATETIMEMAINTAINED": "No",
            "ISLOCATIONSTATUSMAINTAINED": "No",
            "ISSORTORDERCODEMANUAL": "Yes",
            "ISWAREHOUSELOCATIONIDMANUAL": "Yes",
            "LASTACTIVITYDATETIME": "1900-01-01 00:00:00",
            "LASTCOUNTEDUTCDATETIME": "1900-01-01 00:00:00",
            "LOCATIONSTATUS": "Undetermined",
            "PHYSICALDEPTH": "1.000000",
            "PHYSICALHEIGHT": "1.000000",
            "PHYSICALHEIGHTABOVEGROUND": ".000000",
            "PHYSICALMAXIMUMSTORAGEVOLUME": "1.000000",
            "PHYSICALMAXIMUMSTORAGEWEIGHT": ".000000000000",
            "PHYSICALWIDTH": "1.000000",
            "RACKID": "0",
            "SHELFID": "0",
            "SORTORDERCODE": "0",
            "WAREHOUSEAISLEID": "Default",
            "WAREHOUSELOCATIONTYPE": "Buffer",
        } for r in stores]
